server:
    host: http://api.lagen.local
    port: 80
    username: pierre
    password: plop
project_slug: lagen-api
root_dir: features
install:
    - "composer install -vvv"
    - "sed -i.bk s:var/data/data.sqlite:tests/data/data.sqlite: .env"
    - "sed -i.bk s:APP_ENV=dev:APP_ENV=test: .env"
    - "rm .env.bk"
    - "rm -rf var/cache/*"
    - "mkdir -p tests/data tests/config/jwt"
    - "php bin/console doctrine:database:create --env=test"
    - "php bin/console doctrine:schema:update --force --env=test"
    - "openssl genrsa -out tests/config/jwt/private.pem -passout pass:lagen"
    - "openssl rsa -pubout -in tests/config/jwt/private.pem -out tests/config/jwt/public.pem -passin pass:lagen"
test: "./vendor/bin/behat --format=progress"
