server:
    host: http://api.lagen.local
    port: 80
    username: pierre
    password: plop
project_slug: lagen-api
root_dir: features
install:
    - "composer install -vvv"
    - "mkdir -p tests/data tests/config/jwt"
    - "export APP_ENV=test && export DATABASE_PATH=tests/data/data.sqlite"
    - "php bin/console doctrine:database:create --env=test"
    - "php bin/console doctrine:schema:update --force --env=test"
    - "openssl genrsa -out tests/config/jwt/private.pem -passout pass:lagen"
    - "openssl rsa -pubout -in tests/config/jwt/private.pem -out tests/config/jwt/public.pem -passin pass:lagen"
test: "export APP_ENV=test && export DATABASE_PATH=tests/data/data.sqlite && ./vendor/bin/behat --format=progress"
