services:
    app.event.subscriber.origin_http_header:
        class: AppBundle\Event\Subscriber\OriginHttpHeaderSubscriber
        arguments:
            - "%allowed_origins%"
        tags:
            - { name: kernel.event_subscriber }

    app.event.listener.authentication_failure:
        class: AppBundle\Event\Listener\AccessDeniedExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
